name: Simple CI Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  simple-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        run: | 
          echo "Step: Checkout Code"

      - name: Install Dependencies
        run: |
          echo "Step: Install Dependencies"

      - name: Build Application
        run: |
          echo "Step: Build Application"
